apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - role.yaml
  - cluster-role.yaml
  - service-account.yaml
  - role-binding.yaml
  - cluster-role-binding.yaml
  - auth-delegator.clusterrolebinding.yaml
  - cluster-monitoring-role-binding.yaml
  - deployment.yaml
  - routes.yaml
  - service.yaml
  - oauth.secret.yaml
  - fetch-builds-and-images.rbac.yaml
  - image-puller.clusterrolebinding.yaml
  - model-serving-role.yaml
  - model-serving-role-binding.yaml
  - fetch-accelerators.rbac.yaml
  - fetch-hardwares.rbac.yaml
  - fetch-nim-account.rbac.yaml
images:
  - name: oauth-proxy
    # newName: registry.redhat.io/openshift4/ose-oauth-proxy
    newName: registry.tannerjc.net/odh/oauth-proxy-hack:latest
    # digest: sha256:4f8d66597feeb32bb18699326029f9a71a5aca4a57679d636b876377c2e95695
    # digest: sha256:baa4eea958767a4377c95a2db58c5cdc198eb5a68833bdf88015bbdb8a1f3902
    # digest: sha256:17bf5d6adc8cd943788dd7ff202bd8700bc57f6d38f7044f54b0a4c7f69ce89b
    digest: sha256:5b844e570f2f5b64b5a8886a733d8d798bfc35277333923eeae8a0a64ebd0db2
