apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - role.yaml
  - role-binding.yaml
  - model-serving-role.yaml
  - model-serving-role-binding.yaml
  - fetch-hardwares.rbac.yaml
  - fetch-nim-account.rbac.yaml
  - fetch-accelerators.rbac.yaml
  - fetch-builds-and-images.rbac.yaml
  - image-puller.clusterrolebinding.yaml
  - cluster-monitoring-role-binding.yaml
  - auth-delegator.clusterrolebinding.yaml
  - service.yaml
  - deployment.yaml
  - httproute.yaml 